### PR TITLE
Compton has been removed from logos packages.

### PR DESCRIPTION
**Pull request by tperale**
See:
https://github.com/install-logos/logos/commit/90cd1ffc263e2a1f1bf44f21a17a5f09c291409f
Don't know that software, you can still ask to re-add it on the package file :)

### CODE REVIEW

**Comment by joerak** [comment]
oh yeah, it's an aur package. we will add it later on with the scripts.

**Comment by tms23** [comment]
so it is decided to include compton as compositor? 
if so shall i add config? i use window transparency as active window marker instead of more popular window border. what do you guys tink?

**Comment by joerak** [comment]
basically do whatever you like visually - keep the files somewhat clean and readable.
we will decide everything later on. we just need usable and decent configs for now.

and yes, please go ahead and add the config if you like to.

edit: you can ask stuff like that in the gitter chat btw. you should also read what we said about conky.

**Comment by tms23** [comment]
k

**Comment by joerak** [comment]
K DEN

**Pull request merged**
